export const LOAD_STUDENT_CLASS_SCHEDULE = 'monkeys/HomePage/LOAD_STUDENT_CLASS_SCHEDULE';
export const LOAD_STUDENT_CLASS_SCHEDULE_SUCCESS = 'monkeys/HomePage/LOAD_STUDENT_CLASS_SCHEDULE_SUCCESS';
export const LOAD_STUDENT_CLASS_SCHEDULE_ERROR = 'monkeys/HomePage/LOAD_STUDENT_CLASS_SCHEDULE_ERROR';

export const LOAD_CLASS_SCHEDULE = 'monkeys/HomePage/LOAD_CLASS_SCHEDULE';
export const LOAD_CLASS_SCHEDULE_SUCCESS = 'monkeys/HomePage/LOAD_CLASS_SCHEDULE_SUCCESS';
export const LOAD_CLASS_SCHEDULE_ERROR = 'monkeys/HomePage/LOAD_CLASS_SCHEDULE_ERROR';

export const LOAD_STUDENTS = 'app/Attendance/LOAD_STUDENTS';
export const LOAD_STUDENTS_SUCCESS = 'app/Attendance/LOAD_STUDENTS_SUCCESS';
export const LOAD_STUDENTS_ERROR = 'app/Attendance/LOAD_STUDENTS_ERROR';

export const LOAD_CLASS_INSTANCE = 'app/Attendance/LOAD_CLASS_INSTANCE';
export const LOAD_CLASS_INSTANCE_SUCCESS = 'app/Attendance/LOAD_CLASS_INSTANCE_SUCCESS';
export const LOAD_CLASS_INSTANCE_ERROR = 'app/Attendance/LOAD_CLASS_INSTANCE_ERROR';

export const LOAD_STUDENT_CLASS_INSTANCE = 'app/Attendance/LOAD_STUDENT_CLASS_INSTANCE';
export const LOAD_STUDENT_CLASS_INSTANCE_SUCCESS = 'app/Attendance/LOAD_STUDENT_CLASS_INSTANCE_SUCCESS';
export const LOAD_STUDENT_CLASS_INSTANCE_ERROR = 'app/Attendance/LOAD_STUDENT_CLASS_INSTANCE_ERROR';

export const CHANGE_STUDENT_CLASS_INSTANCE_ATTENDANCE = 'app/Attendance/CHANGE_STUDENT_CLASS_INSTANCE_ATTENDANCE';
export const CHANGE_STUDENT_CLASS_INSTANCE_ATTENDANCE_SUCCESS = 'app/Attendance/CHANGE_STUDENT_CLASS_INSTANCE_ATTENDANCE_SUCCESS';
export const CHANGE_STUDENT_CLASS_INSTANCE_ATTENDANCE_ERROR = 'app/Attendance/CHANGE_STUDENT_CLASS_INSTANCE_ATTENDANCE_ERROR';
