export const LOAD_CLASS_SCHEDULE = 'monkeys/HomePage/LOAD_CLASS_SCHEDULE';
export const LOAD_CLASS_SCHEDULE_SUCCESS = 'monkeys/HomePage/LOAD_CLASS_SCHEDULE_SUCCESS';
export const LOAD_CLASS_SCHEDULE_ERROR = 'monkeys/HomePage/LOAD_CLASS_SCHEDULE_ERROR';

